openapi: '3.0.2'
info:
  title: NC News API
  version: '1.0'
servers:
  - url: https://server.test/api
paths:
  /:
    get:
      responses:
        '200':
          description: serves up a json representation of all the available endpoints of the api
  /topics:
    get:
      description: 'serves an array of all topics'
      parameters: []
      responses:
        '200':
          description: OK

        