name: Test & Deploy
on:
 pull_request:
  types:
    - closed
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Use PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
       postgresql db: 'nc_news_test'
       postgresql user: 'test_user'
       postgresql password: 'test_password'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=test_password npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Check if PR is merged
        id: pr-merged
        run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"
      - name: Deploy to Render
        if: steps.pr-merged.outputs.merged == 'true'
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}  